In [4]:
#Importando o Numpy
import numpy as dsa

In [3]:
dsa.__version__

'1.26.4'

In [5]:
#Array criado a partir de uma lista python
arrl = dsa.array([10,21,32,43,48,15,76,57,89])

In [6]:
print(arrl)

[10 21 32 43 48 15 76 57 89]


In [7]:
#Um objeto do tipo ndarray é um recipiente multidimensional de itens do mesmo tipo e tamanho 
type(arrl)

numpy.ndarray

In [8]:
#verificação e formato do array
arrl.shape

(9,)

In [9]:
#Imprimindo um elemento específico no array
arrl[4]

48

In [16]:
#indexação
arrl[1:4]

array([21, 32, 43])

In [17]:
#Indexação
arrl[1:4+1]

array([21, 32, 43, 48])

In [11]:
#Criar uma lista de índices
indices = [1,2,5,6]

In [12]:
#imprimindo os elementos dos indices
arrl[indices]

array([21, 32, 15, 76])

In [13]:
#Criar uma máscara booleana para os elementos pares
mask = (arrl % 2 == 0)

In [14]:
arrl[mask]

array([10, 32, 48, 76])

In [18]:
#Alterando um elemento do array
arrl[0] = 100

In [19]:
print(arrl)

[100  21  32  43  48  15  76  57  89]


In [22]:
#Não é possível incluir elementos de outro tipo
try:
    arrl[0]='Novo elemento'
except:
    print('Operação não permitida')

Operação não permitida


In [23]:
#A função np.array() cria um array NumPy
arr2 = dsa.array([1,2,3,4,5])

In [24]:
print(arr2)

[1 2 3 4 5]


In [25]:
#verificando o tipo do objeto
type(arr2)

numpy.ndarray

In [27]:
#usando métodos do array NumPy
arr2.cumsum()

array([ 1,  3,  6, 10, 15])