In [2]:
#Importando o Numpy
import numpy as dsa

In [3]:
dsa.__version__

'1.26.4'

In [4]:
#Array criado a partir de uma lista python
arrl = dsa.array([10,21,32,43,48,15,76,57,89])

In [5]:
print(arrl)

[10 21 32 43 48 15 76 57 89]


In [6]:
#Um objeto do tipo ndarray é um recipiente multidimensional de itens do mesmo tipo e tamanho 
type(arrl)

numpy.ndarray

In [7]:
#verificação e formato do array
arrl.shape

(9,)

In [8]:
#Imprimindo um elemento específico no array
arrl[4]

48

In [9]:
#indexação
arrl[1:4]

array([21, 32, 43])

In [10]:
#Indexação
arrl[1:4+1]

array([21, 32, 43, 48])

In [11]:
#Criar uma lista de índices
indices = [1,2,5,6]

In [12]:
#imprimindo os elementos dos indices
arrl[indices]

array([21, 32, 15, 76])

In [13]:
#Criar uma máscara booleana para os elementos pares
mask = (arrl % 2 == 0)

In [14]:
arrl[mask]

array([10, 32, 48, 76])

In [15]:
#Alterando um elemento do array
arrl[0] = 100

In [16]:
print(arrl)

[100  21  32  43  48  15  76  57  89]


In [17]:
#Não é possível incluir elementos de outro tipo
try:
    arrl[0]='Novo elemento'
except:
    print('Operação não permitida')

Operação não permitida


In [18]:
#A função np.array() cria um array NumPy
arr2 = dsa.array([1,2,3,4,5])

In [19]:
print(arr2)

[1 2 3 4 5]


In [20]:
#verificando o tipo do objeto
type(arr2)

numpy.ndarray

In [21]:
#usando métodos do array NumPy
arr2.cumsum() #Soma acumulada

array([ 1,  3,  6, 10, 15])

In [22]:
arr2.cumprod() #produto acumulado dos elementos do array

array([  1,   2,   6,  24, 120])

In [23]:
#A função arange cria um array NumPy contendo uma progressão aritmética a partir de um intervalo - start, stop, step
arr3 = dsa.arange(0, 50,5)

In [24]:
print(arr3)

[ 0  5 10 15 20 25 30 35 40 45]


In [25]:
#Verificando o tipo do objeto
type(arr3)

numpy.ndarray

In [26]:
#Formato do array
dsa.shape(arr3)

(10,)

In [27]:
print(arr3.dtype)

int64


In [28]:
#Cria um array preenchido com zeros
arr4 = dsa.zeros(10)
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [29]:
#Retorna 1 nas posições em diagonnal e 0 no restante
arr5 = dsa.eye(3)
print(arr5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
#Os valores passados como parâmetros, formam uma diagonal
arr6 = dsa.diag(dsa.array([1,2,3,4]))
print(arr6)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [31]:
#Array de valores booleanos
arr7 = dsa.array([True, False, False, True])
print(arr7)

[ True False False  True]


In [32]:
#Array de strings
arr8 = dsa.array(['Linguagem Python', 'Linguagem R', 'Linguagem Julia'])
print(arr8)

['Linguagem Python' 'Linguagem R' 'Linguagem Julia']


In [33]:
print(dsa.linspace(0, 10))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [34]:
print(dsa.linspace(0, 10, 15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [35]:
print(dsa.logspace(0,5, 10))

[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]


In [36]:
#Criando uma matriz
arr9 = dsa.array([[1,2,3], [4,5,6]])
type(arr9)

numpy.ndarray

In [37]:
print(arr9)

[[1 2 3]
 [4 5 6]]


In [38]:
print(arr9.shape)

(2, 3)


In [39]:
#Criando uma matriz 2x3 apenas com números '1'
arr10 = dsa.ones((2,3))

In [40]:
print(arr10)

[[1. 1. 1.]
 [1. 1. 1.]]


In [41]:
#listas de listas
lista = [[13,81,22], [0,34,59], [21,48,94]]

In [42]:
#A função matrix cria uma matriz a partir de uma lista de listas
arr11 = dsa.matrix(lista)
type(arr11)

numpy.matrix

In [43]:
print(arr11)

[[13 81 22]
 [ 0 34 59]
 [21 48 94]]


In [44]:
#Formato da matriz
dsa.shape(arr11)

(3, 3)

In [45]:
#Tamanho da matriz
arr11.size

9

In [46]:
#Indexação da matriz
arr11[2,1]

48

In [47]:
arr11[0:2,2]

matrix([[22],
        [59]])

In [48]:
arr11[1,]

matrix([[ 0, 34, 59]])

In [49]:
#Alterando um elemento da matriz
arr11[1,0] = 100

In [50]:
print(arr11)

[[ 13  81  22]
 [100  34  59]
 [ 21  48  94]]


In [51]:
x = dsa.array([1,2])
y = dsa.array([1.0,2.0])
z = dsa.array([1,2], dtype = dsa.float64)

In [52]:
print(x.dtype, y.dtype, z.dtype)

int64 float64 float64


In [53]:
arr12 = dsa.array([[24,76,92,14],[47,35,89,2]], dtype = float)
print(arr12)

[[24. 76. 92. 14.]
 [47. 35. 89.  2.]]


In [54]:
arr12.itemsize

8

In [55]:
arr12.nbytes

64

In [56]:
arr12.ndim

2

In [57]:
#Cria um array numpy de 3 dimensões
arr_3d = dsa.array([
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ],
    [
        [13,14,15,16],
        [17,18,19,20],
        [21,22,23,24]
    ]
])
print(arr_3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [58]:
arr_3d.ndim

3

In [59]:
arr_3d.shape

(2, 3, 4)

In [60]:
arr_3d[0,2,1]

10

In [61]:
#Criar um array numpy de 4 dimensões
arr_4d = dsa.array([
    [
        [
            [1,2,3,4,5],
            [6,7,8,9,10],
            [11,12,13,14,15],
            [16,17,18,19,20]
        ],
        [
            [21,22,23,24,25],
            [26,27,28,29,30],
            [31,32,33,34,35],
            [36,37,38,39,40]
        ],
        [
            [41,42,43,44,45],
            [46,47,48,49,50],
            [51,52,53,54,55],
            [56,57,58,59,60]
        ]
    ],
    [
        [
            [61,62,63,64,65],
            [66,67,68,69,70],
            [71,72,73,74,75],
            [76,77,78,79,80]
        ],
        [
            [81,82,83,84,85],
            [86,87,88,89,90],
            [91,92,93,94,95],
            [96,97,98,99,100]
        ],
        [
            [101,102,103,104,105],
            [106,107,108,109,110],
            [111,112,113,114,115],
            [116,117,118,119,120]
        ]
    ]
])

In [62]:
print(arr_4d)

[[[[  1   2   3   4   5]
   [  6   7   8   9  10]
   [ 11  12  13  14  15]
   [ 16  17  18  19  20]]

  [[ 21  22  23  24  25]
   [ 26  27  28  29  30]
   [ 31  32  33  34  35]
   [ 36  37  38  39  40]]

  [[ 41  42  43  44  45]
   [ 46  47  48  49  50]
   [ 51  52  53  54  55]
   [ 56  57  58  59  60]]]


 [[[ 61  62  63  64  65]
   [ 66  67  68  69  70]
   [ 71  72  73  74  75]
   [ 76  77  78  79  80]]

  [[ 81  82  83  84  85]
   [ 86  87  88  89  90]
   [ 91  92  93  94  95]
   [ 96  97  98  99 100]]

  [[101 102 103 104 105]
   [106 107 108 109 110]
   [111 112 113 114 115]
   [116 117 118 119 120]]]]


In [63]:
arr_4d.ndim

4

In [64]:
arr_4d.shape

(2, 3, 4, 5)

In [65]:
arr_4d[0,2,1]

array([46, 47, 48, 49, 50])

In [66]:
arr_4d[0,2,1,4]

50